name: Update README

on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "templates/profile.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          commit_message: 'docs: Update generated README [skip ci]'
          branch: main
          commit_user_name: 'HelloTools Bot'
          commit_user_email: bot@932.moe
          commit_author: HelloTools Bot <bot@932.moe>
